from typing import Final, Literal

CAPTURE_BATCH_DEFAULT_STATUS: Final[Literal["queued"]] = "queued"

CAPTURE_BATCH_ID_MAX_LENGTH = 64
CAPTURE_SOURCE_NAME_MAX_LENGTH = 128
CAPTURE_SOURCE_ENDPOINT_MAX_LENGTH = 128
CAPTURE_ROUTE_KIND_MAX_LENGTH = 32
CAPTURE_PAGE_CURSOR_MAX_LENGTH = 128
CAPTURE_CHECKSUM_MAX_LENGTH = 128
